set serveroutput on;
    DECLARE
        CNT1 NUMBER(2);            
    BEGIN  
    
	DBMS_OUTPUT.PUT_LINE ('Adding column UNITS_PICKED_COUNT to POOL_REDELIVERY table');  
    SELECT COUNT(*) INTO CNT1 FROM USER_TAB_COLS WHERE COLUMN_NAME = 'UNITS_PICKED_COUNT' AND TABLE_NAME = 'POOL_REDELIVERY'; 
    IF CNT1 > 0 THEN
        DBMS_OUTPUT.PUT_LINE ('COLUMN UNITS_PICKED_COUNT ALREADY EXISTS');
    ELSE
        EXECUTE IMMEDIATE 'ALTER TABLE POOL_REDELIVERY ADD UNITS_PICKED_COUNT NUMBER(5)';
		DBMS_OUTPUT.PUT_LINE ('Column UNITS_PICKED_COUNT added to POOL_REDELIVERY table');       
    END IF;
    
END;
/ 
      
